### PR TITLE
Fix message usage for all commands

### LINKED ISSUE #343: Fix findn and findp message usage

### PR DESCRIPTION
**Pull request by geeliette**
Fixes #343

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -24,7 +24,7 @@ public class AddCommand extends Command {
 
     public static final String COMMAND_WORD = "add";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds a reservation to the address book. "
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds a reservation to the address book.\n"
```
Comment (CVincent0907) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:27]: Adds reservation to gastrobook instead of address book

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 2]
```diff
@@ -18,11 +18,11 @@ public class DeleteCommand extends Command {
     public static final String COMMAND_WORD = "delete";
 
     public static final String MESSAGE_USAGE = COMMAND_WORD
-            + ": Deletes the person identified by the index number used in the displayed Reservation list.\n"
-            + "Parameters:  ID ( [6 figures of date (ie : ddMMyyyy)) of TODAY or TOMORROW] "
-            + "+ [last 4 digits of customer phone number (ie:xxxx)]"
-            + "+ [time of reservation in HHMM format])"
-            + "Example: " + COMMAND_WORD + " 1";
+            + ": Deletes the person identified by the ID used in the displayed reservation list.\n"
```
Comment (CVincent0907) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java:21]: Deletes the reservation instead of person

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 3]
```diff
@@ -34,7 +34,7 @@ public class AddCommand extends Command {
             + PREFIX_PAX + "PAX "
             + PREFIX_TABLE + "TABLE "
             + "[" + PREFIX_TAG + "TAG]... "
-            + "[" + PREFIX_REMARK + "REMARK]. "
+            + "[" + PREFIX_REMARK + "REMARK].\n"
```
Comment (CVincent0907) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:37]: This remark field can be deleted. @Frozennfishh  says he will remove this option for add field since remark provides the functionality.

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 4]
```diff
@@ -44,7 +44,8 @@ public class AddCommand extends Command {
             + PREFIX_PAX + "2 "
             + PREFIX_TABLE + "A1 "
             + PREFIX_TAG + "regular "
-            + PREFIX_TAG + "event ";
+            + PREFIX_TAG + "event "
+            + PREFIX_REMARK + "he likes cheese";
```
Comment (CVincent0907) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:48]: This also

File: src/main/java/seedu/address/logic/commands/FindByNameCommand.java [hunk 5]
```diff
@@ -16,10 +16,10 @@ public class FindByNameCommand extends Command {
 
     public static final String COMMAND_WORD = "findn";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all persons whose names contain any of "
-            + "the specified keywords (case-insensitive) and displays reservations made by them for today or "
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all persons whose names match any of "
+            + "the specified names (case-insensitive) and displays reservations made by them for today or "
             + "tomorrow as a list with index numbers.\n"
```
Comment (CVincent0907) [inline src/main/java/seedu/address/logic/commands/FindByNameCommand.java:21]: list wirh reservation ID instead of index numbers

**Review by CVincent0907 — CHANGES_REQUESTED** [review]
