### PR TITLE
Fix Remark Message

### LINKED ISSUE #171: Remark message not up to daye
Image

@Frozennfishh  Should the remark of person be remark of that particular reservation ?

### PR DESCRIPTION
**Pull request by Frozennfishh**
Fix #171

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/RemarkCommand.java [hunk 1]
```diff
@@ -17,8 +17,8 @@ public class RemarkCommand extends Command {
 
     public static final String COMMAND_WORD = "remark";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Edits the remark of the person identified "
-            + "by the index number used in the last person listing. "
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Edits the remark of the input reservation "
+            + "by the reservation ID. "
             + "Existing remark will be overwritten by the input.\n"
             + "Parameters:  ID ( [6 figures of date (ie : ddMMyyyy)) of TODAY or TOMORROW] "
             + "+ [last 4 digits of customer phone number (ie:xxxx)]"
```
Comment (caroline1233456) [inline src/main/java/seedu/address/logic/commands/RemarkCommand.java:24]: I think the ID also need to change? should be 
Parameters:  ID ( [6 figures of date (ie : ddMMyyyy)) of TODAY or TOMORROW] "
            + "+ [last 4 digits of customer phone number (ie:xxxx)]"
            + "+ [time of reservation in HHMM format])

**Review by caroline1233456 — APPROVED** [review]
LGTM, the parameter ID also need to be updated
