### PR TITLE
Fix bug for mark and unmark command

### LINKED ISSUE #200: Able to mark/unmark commands that are already paid/unpaid
Quite a minor issue, but maybe can change the output message when user tries to mark/unmark a reservation that is already paid/unpaid to something like "Reservation is already marked as paid"? If not I think it's also okay, but may be something that people nitpick on

### PR DESCRIPTION
**Pull request by caroline1233456**
Fix #200

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/MarkCommand.java [hunk 1]
```diff
@@ -22,6 +22,7 @@ public class MarkCommand extends Command {
             + "Example: " + COMMAND_WORD + " 180320251234 ";
 
     public static final String MESSAGE_MARK_RESERVATION_SUCCESS = "Successfully marks the reservation";
+    public static final String MESSAGE_DUPLICATE_MARK = "The reservation has been marked";
```
Comment (geeliette) [inline src/main/java/seedu/address/logic/commands/MarkCommand.java:25]: Maybe can change to "The reservation has already been marked as paid" to match the message_duplicate_unmark

**Review by Frozennfishh — CHANGES_REQUESTED** [review]
Same comment as @geeliette, also correct checkstyle for `MarkCommand` and `UnmarkCommand` classes
